// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gentela_Alela.Models;

#nullable disable

namespace gentela_Alela.Migrations
{
    [DbContext(typeof(GentleProjectContext))]
    [Migration("20260420065515_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gentela_Alela.Models.AddtionalDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caste")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Disability")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("disability");

                    b.Property<bool?>("Isdeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Upidno")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("UPIDNO");

                    b.HasKey("Id")
                        .HasName("PK__Addtiona__3213E83FC634CFA0");

                    b.ToTable("AddtionalDetails");
                });

            modelBuilder.Entity("gentela_Alela.Models.CommunicationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<bool?>("Isdeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isdeleted");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id")
                        .HasName("PK__Communic__3213E83F674864CD");

                    b.ToTable("CommunicationDetails");
                });

            modelBuilder.Entity("gentela_Alela.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Country__3214EC0705AB240B");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("gentela_Alela.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DistrictName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__District__3214EC07FDC0818E");

                    b.HasIndex("StateId");

                    b.ToTable("District", (string)null);
                });

            modelBuilder.Entity("gentela_Alela.Models.DomicileVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DomicileOption")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("Isdeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isdeleted");

                    b.Property<string>("NameAsPerRtionOrcet")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NameAsPerRtionORCet");

                    b.Property<string>("RationOrcetNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RationORCetNumber");

                    b.HasKey("Id")
                        .HasName("PK__Domicile__3213E83FDC00CB46");

                    b.ToTable("DomicileVerification", (string)null);
                });

            modelBuilder.Entity("gentela_Alela.Models.EducationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CollegeName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CourseType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Isdelted")
                        .HasColumnType("bit")
                        .HasColumnName("isdelted");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("ResultDate")
                        .HasColumnType("date");

                    b.Property<string>("UniversityName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("YearOfPassout")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Educatio__3214EC07B03D7112");

                    b.ToTable("EducationDetails");
                });

            modelBuilder.Entity("gentela_Alela.Models.LoginDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<bool?>("Isdeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__LoginDet__3213E83FC24F14A3");

                    b.ToTable("LoginDetails");
                });

            modelBuilder.Entity("gentela_Alela.Models.PersonalDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("DistrictID");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FullName")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool?>("Isdeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Password")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProfileImage")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int?>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("StateID");

                    b.HasKey("Id")
                        .HasName("PK__Personal__3214EC07E19520D1");

                    b.HasIndex("CountryId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("RoleId");

                    b.HasIndex("StateId");

                    b.ToTable("Personal_Details", (string)null);
                });

            modelBuilder.Entity("gentela_Alela.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Registra__3213E83FA14A79DA");

                    b.ToTable("Registration", (string)null);
                });

            modelBuilder.Entity("gentela_Alela.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Isdeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isdeleted");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Role__3213E83F41DF49C4");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("gentela_Alela.Models.RouteLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParamId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RouteLinks");
                });

            modelBuilder.Entity("gentela_Alela.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__State__3214EC0754447B01");

                    b.HasIndex("CountryId");

                    b.ToTable("State", (string)null);
                });

            modelBuilder.Entity("gentela_Alela.Models.Taluk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DistictId")
                        .HasColumnType("int")
                        .HasColumnName("distictId");

                    b.Property<string>("TalukName")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Taluk_Name");

                    b.HasKey("Id")
                        .HasName("PK__Taluk__3213E83FFF2239E7");

                    b.HasIndex("DistictId");

                    b.ToTable("Taluk", (string)null);
                });

            modelBuilder.Entity("gentela_Alela.Models.YuvanidhiApplicantDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdditionalId")
                        .HasColumnType("int")
                        .HasColumnName("additionalId");

                    b.Property<string>("Address1")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Address2")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("address2");

                    b.Property<string>("AdharName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("CommunicationId")
                        .HasColumnType("int")
                        .HasColumnName("communicationId");

                    b.Property<int?>("DistinctId")
                        .HasColumnType("int")
                        .HasColumnName("distinctID");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<int?>("DomicineId")
                        .HasColumnType("int")
                        .HasColumnName("domicineId");

                    b.Property<int?>("EducationId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gender");

                    b.Property<bool?>("Isdeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isdeleted");

                    b.Property<string>("PernmentAdress")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("pernmentAdress");

                    b.Property<string>("Photo")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("TalukId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Yuvanidh__3214EC07763CC972");

                    b.HasIndex("AdditionalId");

                    b.HasIndex("CommunicationId");

                    b.HasIndex("DistinctId");

                    b.HasIndex("DomicineId");

                    b.HasIndex("EducationId");

                    b.HasIndex("TalukId");

                    b.ToTable("Yuvanidhi_Applicant_Details", (string)null);
                });

            modelBuilder.Entity("gentela_Alela.Models.District", b =>
                {
                    b.HasOne("gentela_Alela.Models.State", "State")
                        .WithMany("Districts")
                        .HasForeignKey("StateId")
                        .HasConstraintName("FK__District__StateI__07C12930");

                    b.Navigation("State");
                });

            modelBuilder.Entity("gentela_Alela.Models.PersonalDetail", b =>
                {
                    b.HasOne("gentela_Alela.Models.Country", "Country")
                        .WithMany("PersonalDetails")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK__Personal___Count__2BFE89A6");

                    b.HasOne("gentela_Alela.Models.District", "District")
                        .WithMany("PersonalDetails")
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("FK__Personal___Distr__2DE6D218");

                    b.HasOne("gentela_Alela.Models.Role", "Role")
                        .WithMany("PersonalDetails")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Personal___RoleI__2B0A656D");

                    b.HasOne("gentela_Alela.Models.State", "State")
                        .WithMany("PersonalDetails")
                        .HasForeignKey("StateId")
                        .HasConstraintName("FK__Personal___State__2CF2ADDF");

                    b.Navigation("Country");

                    b.Navigation("District");

                    b.Navigation("Role");

                    b.Navigation("State");
                });

            modelBuilder.Entity("gentela_Alela.Models.State", b =>
                {
                    b.HasOne("gentela_Alela.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK__State__CountryId__04E4BC85");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("gentela_Alela.Models.Taluk", b =>
                {
                    b.HasOne("gentela_Alela.Models.District", "Distict")
                        .WithMany("Taluks")
                        .HasForeignKey("DistictId")
                        .HasConstraintName("FK__Taluk__distictId__3C34F16F");

                    b.Navigation("Distict");
                });

            modelBuilder.Entity("gentela_Alela.Models.YuvanidhiApplicantDetail", b =>
                {
                    b.HasOne("gentela_Alela.Models.AddtionalDetail", "Additional")
                        .WithMany("YuvanidhiApplicantDetails")
                        .HasForeignKey("AdditionalId")
                        .HasConstraintName("FK__Yuvanidhi__addit__09746778");

                    b.HasOne("gentela_Alela.Models.CommunicationDetail", "Communication")
                        .WithMany("YuvanidhiApplicantDetails")
                        .HasForeignKey("CommunicationId")
                        .HasConstraintName("FK__Yuvanidhi__commu__0880433F");

                    b.HasOne("gentela_Alela.Models.District", "Distinct")
                        .WithMany("YuvanidhiApplicantDetails")
                        .HasForeignKey("DistinctId")
                        .HasConstraintName("FK__Yuvanidhi__disti__43D61337");

                    b.HasOne("gentela_Alela.Models.DomicileVerification", "Domicine")
                        .WithMany("YuvanidhiApplicantDetails")
                        .HasForeignKey("DomicineId")
                        .HasConstraintName("FK__Yuvanidhi__domic__078C1F06");

                    b.HasOne("gentela_Alela.Models.EducationDetail", "Education")
                        .WithMany("YuvanidhiApplicantDetails")
                        .HasForeignKey("EducationId")
                        .HasConstraintName("FK__Yuvanidhi__Educa__0697FACD");

                    b.HasOne("gentela_Alela.Models.Taluk", "Taluk")
                        .WithMany("YuvanidhiApplicantDetails")
                        .HasForeignKey("TalukId")
                        .HasConstraintName("FK__Yuvanidhi__Taluk__44CA3770");

                    b.Navigation("Additional");

                    b.Navigation("Communication");

                    b.Navigation("Distinct");

                    b.Navigation("Domicine");

                    b.Navigation("Education");

                    b.Navigation("Taluk");
                });

            modelBuilder.Entity("gentela_Alela.Models.AddtionalDetail", b =>
                {
                    b.Navigation("YuvanidhiApplicantDetails");
                });

            modelBuilder.Entity("gentela_Alela.Models.CommunicationDetail", b =>
                {
                    b.Navigation("YuvanidhiApplicantDetails");
                });

            modelBuilder.Entity("gentela_Alela.Models.Country", b =>
                {
                    b.Navigation("PersonalDetails");

                    b.Navigation("States");
                });

            modelBuilder.Entity("gentela_Alela.Models.District", b =>
                {
                    b.Navigation("PersonalDetails");

                    b.Navigation("Taluks");

                    b.Navigation("YuvanidhiApplicantDetails");
                });

            modelBuilder.Entity("gentela_Alela.Models.DomicileVerification", b =>
                {
                    b.Navigation("YuvanidhiApplicantDetails");
                });

            modelBuilder.Entity("gentela_Alela.Models.EducationDetail", b =>
                {
                    b.Navigation("YuvanidhiApplicantDetails");
                });

            modelBuilder.Entity("gentela_Alela.Models.Role", b =>
                {
                    b.Navigation("PersonalDetails");
                });

            modelBuilder.Entity("gentela_Alela.Models.State", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("PersonalDetails");
                });

            modelBuilder.Entity("gentela_Alela.Models.Taluk", b =>
                {
                    b.Navigation("YuvanidhiApplicantDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
